# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image
FROM node:24-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install project dependencies
RUN npm install

# Copy the entire project directory
COPY . .

# Build the project
RUN npm run build

# Start a new stage for the final image
FROM node:24-alpine AS release

# Add MCP registry validation label
LABEL io.modelcontextprotocol.server.name="io.github.domdomegg/airtable-mcp-server"

# Set working directory
WORKDIR /app

# Copy the build files from the previous stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json 
COPY --from=builder /app/node_modules /app/node_modules

# Set the entry point to run the server
ENTRYPOINT ["node", "dist/main.js"]
